# -*- coding: utf-8 -*-
"""CS335_PythonLab1_VISHANPATEL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17h8kr2_sqpams04u31WqfKOa6asYhxMj
"""

name = "Vishan Patel"
age = 25
ai_course = True

print(f"My name is {name},\nAge in 5 years: {age + 5}, \nIs enrolled in CS 335 course? {ai_course}.")

topics = ["Logic", "Search", "NLP", "ML", "Bayesian Inference", "Database Management", "Web Designing"]
print("We will study:")
for i, topic in enumerate(topics, start=1):
    print(f"{i}. {topic}")

student = {"name": "Vishan", "score": 97}

if student["score"] >= 95:
    grade = "A+"
elif student["score"] >= 90:
    grade = "A"
elif student["score"] >= 80:
    grade = "B"
else:
    grade = "C or below"

print(f"{student['name']} received a grade of {grade}.")

def square_number(num):
    return num ** 2

print(square_number(3))
print(square_number(5))